import {REACT_NATIVE_SUPABASE_URL, REACT_NATIVE_SUPABASE_ANON_KEY} from '@env'

export const SUPABASE_URL = REACT_NATIVE_SUPABASE_URL || ''
export const SUPABASE_ANON_KEY = REACT_NATIVE_SUPABASE_ANON_KEY || ''
